name: Check Git Flow Rules – PR

on:
  pull_request:
    branches: ["main", "develop", "release/*", "release-*"]
    types: ["opened", "synchronize", "reopened"]

permissions:
  contents: read

jobs:
  validate-gitflow-rules:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate Git Flow rules
        shell: bash
        run: |
          set -euo pipefail

          SOURCE_BRANCH="${GITHUB_HEAD_REF}"
          TARGET_BRANCH="${GITHUB_BASE_REF}"

          echo "Validando GitFlow..."
          echo "📌 PR source branch: $SOURCE_BRANCH"
          echo "➡ PR target branch: $TARGET_BRANCH"

          fail() {
            echo "❌ ERROR: $1"
            exit 1
          }

          # Regla #1: PR hacia main solo desde release-* o hotfix-*
          if [ "$TARGET_BRANCH" == "main" ]; then
            if [[ ! "$SOURCE_BRANCH" =~ ^(release-|release/|hotfix-|hotfix/) ]]; then
              fail "PR hacia main debe provenir de release-* o hotfix-*"
            fi
          fi

          # Regla #2: PR hacia release/* solo desde develop
          if [[ "$TARGET_BRANCH" =~ ^(release-|release/) ]]; then
            if [ "$SOURCE_BRANCH" != "develop" ]; then
              fail "PR hacia release-* debe provenir de develop"
            fi
          fi

          echo "✅ Git Flow: Todas las reglas pasan!"
